// Generated by https://quicktype.io

export interface Usuario {
    usuario: UsuarioClass;
    token:   string;
}

export interface UsuarioClass {
    rol:    string;
    estado: boolean;
    google: boolean;
    nombre: string;
    correo: string;
    uid:    string;
}
// Generated by https://quicktype.io

export interface LoginData {
    correo:   string;
    password: string;
}
// Generated by https://quicktype.io

export interface RegisterData {
    nombre:   string;
    correo:   string;
    password: string;
}
